[package]
name = "PSM"
version = "0.1.0"
authors = ["Jeffrey Goldberg <jeff@agilebits.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zxcvbn = "1.0.2"
float-cmp = "0.5.2"
